name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .
        docker tag ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest ${{ secrets.DOCKER_USERNAME }}/wisecow-app:${{ github.sha }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:${{ github.sha }}

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Set up Kubernetes context
      run: |
        kubectl config set-cluster my-cluster --server=${{ secrets.KUBE_API_SERVER }} --certificate-authority=${{ secrets.KUBE_CA_CRT }}
        kubectl config set-credentials my-user --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context my-context --cluster=my-cluster --user=my-user
        kubectl config use-context my-context

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/wisecow-deployment.yaml
        kubectl apply -f k8s/wisecow-service.yaml

